todo34/todo_34/config/routes.rb
Todo34::Application.routes.draw do
  resources :puppies

  resources :breeds

end

todo34/todo_34/app/models/breed.rb
class Breed < ActiveRecord::Base
  attr_accessible :name

  has_many :puppies
end

todo34/todo_34/app/models/puppy.rb
class Puppy < ActiveRecord::Base
  attr_accessible :breed_id, :content

  belongs_to :breed
end

todo34/todo_34/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

todo34/todo_34/app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  # GET /breeds
  # GET /breeds.json
  def index
    @breeds = Breed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @breeds }
    end
  end

  # GET /breeds/1
  # GET /breeds/1.json
  def show
    @breed = Breed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @breed }
    end
  end

  # GET /breeds/new
  # GET /breeds/new.json
  def new
    @breed = Breed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @breed }
    end
  end

  # GET /breeds/1/edit
  def edit
    @breed = Breed.find(params[:id])
  end

  # POST /breeds
  # POST /breeds.json
  def create
    @breed = Breed.new(params[:breed])

    respond_to do |format|
      if @breed.save
        format.html { redirect_to @breed, notice: 'Breed was successfully created.' }
        format.json { render json: @breed, status: :created, location: @breed }
      else
        format.html { render action: "new" }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /breeds/1
  # PUT /breeds/1.json
  def update
    @breed = Breed.find(params[:id])

    respond_to do |format|
      if @breed.update_attributes(params[:breed])
        format.html { redirect_to @breed, notice: 'Breed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1
  # DELETE /breeds/1.json
  def destroy
    @breed = Breed.find(params[:id])
    @breed.destroy

    respond_to do |format|
      format.html { redirect_to breeds_url }
      format.json { head :no_content }
    end
  end
end

todo34/todo_34/app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  # GET /puppies
  # GET /puppies.json
  def index
    @puppies = Puppy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @puppies }
    end
  end

  # GET /puppies/1
  # GET /puppies/1.json
  def show
    @puppy = Puppy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @puppy }
    end
  end

  # GET /puppies/new
  # GET /puppies/new.json
  def new
    @puppy = Puppy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @puppy }
    end
  end

  # GET /puppies/1/edit
  def edit
    @puppy = Puppy.find(params[:id])
  end

  # POST /puppies
  # POST /puppies.json
  def create
    @puppy = Puppy.new(params[:puppy])

    respond_to do |format|
      if @puppy.save
        format.html { redirect_to @puppy, notice: 'Puppy was successfully created.' }
        format.json { render json: @puppy, status: :created, location: @puppy }
      else
        format.html { render action: "new" }
        format.json { render json: @puppy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /puppies/1
  # PUT /puppies/1.json
  def update
    @puppy = Puppy.find(params[:id])

    respond_to do |format|
      if @puppy.update_attributes(params[:puppy])
        format.html { redirect_to @puppy, notice: 'Puppy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @puppy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puppies/1
  # DELETE /puppies/1.json
  def destroy
    @puppy = Puppy.find(params[:id])
    @puppy.destroy

    respond_to do |format|
      format.html { redirect_to puppies_url }
      format.json { head :no_content }
    end
  end
end

todo34/todo_34/app/helpers/application_helper.rb
module ApplicationHelper
end

todo34/todo_34/app/helpers/breeds_helper.rb
module BreedsHelper
end

todo34/todo_34/app/helpers/puppies_helper.rb
module PuppiesHelper
end

todo34/todo_34/app/views/breeds/_form.html.erb
<%= form_for(@breed) do |f| %>
  <% if @breed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
      <% @breed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

todo34/todo_34/app/views/breeds/edit.html.erb
<h1>Editing breed</h1>

<%= render 'form' %>

<%= link_to 'Show', @breed %> |
<%= link_to 'Back', breeds_path %>

todo34/todo_34/app/views/breeds/index.html.erb
<h1>Listing breeds</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @breeds.each do |breed| %>
  <tr>
    <td><%= breed.name %></td>
    <td><%= link_to 'Show', breed %></td>
    <td><%= link_to 'Edit', edit_breed_path(breed) %></td>
    <td><%= link_to 'Destroy', breed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Breed', new_breed_path %>

todo34/todo_34/app/views/breeds/new.html.erb
<h1>New breed</h1>

<%= render 'form' %>

<%= link_to 'Back', breeds_path %>

todo34/todo_34/app/views/breeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @breed.name %>
</p>


<%= link_to 'Edit', edit_breed_path(@breed) %> |
<%= link_to 'Back', breeds_path %>

todo34/todo_34/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo34</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

todo34/todo_34/app/views/puppies/_form.html.erb
<%= form_for(@puppy) do |f| %>
  <% if @puppy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puppy.errors.count, "error") %> prohibited this puppy from being saved:</h2>

      <ul>
      <% @puppy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :breed_id %><br />
    <%= f.number_field :breed_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

todo34/todo_34/app/views/puppies/edit.html.erb
<h1>Editing puppy</h1>

<%= render 'form' %>

<%= link_to 'Show', @puppy %> |
<%= link_to 'Back', puppies_path %>

todo34/todo_34/app/views/puppies/index.html.erb
<h1>Listing puppies</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Breed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @puppies.each do |puppy| %>
  <tr>
    <td><%= puppy.content %></td>
    <td><%= puppy.breed_id %></td>
    <td><%= link_to 'Show', puppy %></td>
    <td><%= link_to 'Edit', edit_puppy_path(puppy) %></td>
    <td><%= link_to 'Destroy', puppy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Puppy', new_puppy_path %>

todo34/todo_34/app/views/puppies/new.html.erb
<h1>New puppy</h1>

<%= render 'form' %>

<%= link_to 'Back', puppies_path %>

todo34/todo_34/app/views/puppies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @puppy.content %>
</p>

<p>
  <b>Breed:</b>
  <%= @puppy.breed_id %>
</p>


<%= link_to 'Edit', edit_puppy_path(@puppy) %> |
<%= link_to 'Back', puppies_path %>